# Generated by Django 4.2 on 2023-05-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('specialty', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Radiology', 'Radiology'), ('Dermatology', 'Dermatology'), ('Oncology', 'Oncology')], max_length=50)),
                ('rank', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Consultant', 'Consultant'), ('Associate Professor', 'Associate Professor'), ('Registrar', 'Registrar'), ('Senior Registrar', 'Senior Registrar'), ('Specialist', 'Specialist')], max_length=50)),
            ],
        ),
    ]
