# Generated by Django 4.2 on 2023-05-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('MRN', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('nationality', models.CharField(choices=[('Saudi', 'Saudi'), ('Non-Saudi', 'Non-Saudi')], max_length=9)),
                ('physician', models.CharField(max_length=255)),
                ('clinical_indication', models.CharField(max_length=255)),
                ('provisional_diagnosis', models.CharField(max_length=255)),
                ('unit_name', models.CharField(choices=[('ER', 'Emergency Room'), ('pedia_ward', 'Paediatrics Ward'), ('male_ward', 'Male Ward'), ('female_ward', 'Female Ward'), ('OB_ward', 'Obstetrics Ward'), ('L&D_ward', 'Labour / Delivery Ward'), ('covid_ward', 'Covid Ward'), ('OPD', 'Outpatient Department'), ('referral', 'Referral')], max_length=20)),
                ('status', models.CharField(choices=[('emergency', 'Emergency/Immediately'), ('urgent', 'Urgent/24hrs'), ('routine', 'Routine/48 hours')], max_length=20)),
                ('way_of_transport', models.CharField(choices=[('walking', 'Walking'), ('wheelchair', 'Wheelchair'), ('trolley', 'Trolley')], max_length=20)),
                ('is_new_request', models.CharField(choices=[('new', 'New Request'), ('followup', 'Follow Up')], max_length=20)),
                ('modalities', models.CharField(choices=[('CT', 'CT'), ('US', 'US'), ('X_ray', 'X-ray'), ('MRI', 'MRI'), ('Mammography', 'Mammography'), ('Angiogram', 'Angiogram'), ('Interventional_radiological_procedures', 'Interventional radiological procedures'), ('Fluoroscopy', 'Fluoroscopy'), ('Nuclear_medicine_imaging', 'Nuclear medicine imaging'), ('Molecular_Imaging_PET_scanning', 'Molecular Imaging /Positron Emission Tomography /PET scanning'), ('Bedside_critical_care_radiography', 'Bedside /critical care radiography'), ('Portable_radiological_machines', 'Portable radiological machines')], max_length=50)),
                ('study_part', models.CharField(blank=True, choices=[('', 'Study Part'), ('Abdomen', 'Abdomen'), ('KUB', 'KUB'), ('OB_less_than_14_Weeks', 'OB less than 14 Weeks'), ('OB_more_than_14_Weeks', 'OB more than 14 Weeks'), ('Brain', 'Brain'), ('Neck', 'Neck'), ('Chest', 'Chest'), ('Pelvis', 'Pelvis'), ('Pan-CT', 'pan-CT'), ('Thyroid', 'Thyroid'), ('Breast', 'Breast'), ('Scrotal', 'Scrotal'), ('Cervical_spine', 'Cervical spine'), ('L_S_spine', 'L/S spine'), ('D_L_spine', 'D/L spine'), ('Doppler-venous-lower', 'doppler-venous-lower'), ('Doppler-arterial-lower', 'doppler-arterial-lower'), ('Doppler-venous-upper', 'doppler-venous-upper'), ('Doppler-arterial-upper', 'doppler-arterial-upper'), ('Elbow', 'Elbow'), ('Wrist_hand', 'Wrist/hand'), ('Pelvis_hip', 'Pelvis/hip'), ('Knee', 'Knee'), ('Ankle_foot', 'Ankle/foot')], default='', max_length=50)),
                ('side_label', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('none', 'None')], max_length=50)),
                ('need_contrast', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('contrast_specification', models.CharField(choices=[('oral', 'Oral'), ('iv', 'IV Contrast'), ('oral_iv', 'Oral and IV Contrast'), ('no_contrast', 'No Contrast')], max_length=50)),
                ('is_allergy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('allergy_specification', models.CharField(max_length=255)),
                ('other_study', models.CharField(max_length=255)),
                ('date_of_request', models.DateField()),
            ],
        ),
    ]
